# Generated by Django 3.2.13 on 2022-06-15 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCoder', '0002_integrantes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Integrantes',
        ),
    ]
